data_path: /media/marcel/Data1/Datasets/waymo-od
# convnext, convnext_pretrained, unet
model: "convnext_pretrained"
epochs: 5
batch_size: 1
learning_rate: 1.0e-05
load_checkpoint: null       # e.g. StixelNExT_Pro_volcanic-spaceship-170_epoch-31_test-error-0.2544909715652466.pth or null to not load a checkpoint
logging: true               # Wandb
early_stop:
  tol: 8                    # tolerance
  min_delta: 0.00001        # minimum improvement after {tolerance} iterations
# loss weights
P: 1.0
h: 1.0
vB: 1.0
d: 1.0
h_d_ratio: 1.0